# Generated by Django 3.0.7 on 2020-06-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imgs', models.TextField()),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates_lat', models.FloatField()),
                ('coordinates_lng', models.FloatField()),
            ],
        ),
    ]
