# Generated by Django 3.0.7 on 2020-06-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200607_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature1', to='places.Image'),
        ),
        migrations.AddField(
            model_name='feature',
            name='image2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature2', to='places.Image'),
        ),
    ]
