# Generated by Django 3.0.7 on 2020-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200607_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='placeId',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
