# Generated by Django 3.0.7 on 2020-06-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_feature_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
