# Generated by Django 3.0.7 on 2020-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200608_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
