# Generated by Django 3.0.7 on 2020-06-10 04:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20200610_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
    ]
